/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--bg)",
        foreground: "var(--fg)",
        muted: "var(--fg-muted)",
        "bg-soft": "var(--bg-soft)",
        surface: "var(--surface)",
        surface2: "var(--surface-2)",
        border: "var(--border)",
        borderStrong: "var(--border-strong)",
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          fg: "var(--accent-fg)",
          soft: "var(--accent-soft)",
          2: "var(--accent-2)",
        },
        rival: "var(--accent-2)",
        link: "var(--link)",
        success: "var(--success)",
        successStrong: "var(--success-strong)",
        warn: "var(--warn)",
        danger: "var(--danger)",
        code: "var(--code-bg)",
        codeFg: "var(--code-fg)",
        codeBorder: "var(--code-border)",
        lineNo: "var(--line-no)",
        // Legacy brand aliases
        paper: "#FAF6F0",
        ink: "#0A0A0A",
        vermillion: "#FF3B30",
        blueprint: "#0A84FF",
        zinc: {
          50: "#FAFAFA",
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A3A3A3",
          500: "#737373",
          600: "#52525B",
          700: "#3F3F46",
          800: "#27272A",
          900: "#18181B",
          950: "#09090B",
        },
      },
      fontFamily: {
        display: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        arena: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        none: "0px",
        sm: "6px",
        DEFAULT: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px #0A0A0A",
        "brutal-sm": "2px 2px 0px 0px #0A0A0A",
        "brutal-lg": "6px 6px 0px 0px #0A0A0A",
      },
      animation: {
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
