"""Skills module for Agent Arena.

Exposes canonical skill identity, lifecycle tracking, context ranking,
authoritative attribution, and Skill Graph v0.3 catalog metadata (D0).
"""

from .canonical import (
    CanonicalSkillResolver,
    SkillRecord,
    normalize_skill_ref,
    parse_skill_text,
    slugify,
)
from .canonical_metadata import (
    CATALOG_VERSION,
    SCHEMA_VERSION,
    CanonicalSkillCatalog,
    CatalogValidationError,
    apply_canonical_metadata,
    canonical_metadata_for,
    load_canonical_catalog,
    validate_catalog_documents,
)
from .discovery import (
    CompactSkillCard,
    DiscoveryRequestError,
    DiscoveryErrorView,
    IndexDiscoveryView,
    RootDiscoveryView,
    RootIndexCard,
    SearchDiscoveryView,
    SkillDiscoveryView,
    browse_index,
    browse_roots,
    discover_skills,
    format_discovery_text,
    inspect_skill_card,
    is_public_skill,
    score_skill_for_query,
    search_skills,
    skill_to_compact_card,
)
from .graph import (
    SkillGraph,
    SkillGraphIndex,
    UnknownIndexError,
    UnknownSkillError,
    all_indexes,
    all_skills,
    child_indexes,
    get_index,
    get_skill,
    indexes_for_skill,
    load_skill_graph,
    related_skills,
    require_index,
    require_skill,
    root_indexes,
    skills_in_index,
    suggested_foundations,
)
from .lifecycle import SkillLifecycleTracker
from .ranking import (
    RankedSkillScore,
    compute_semantic_relevance,
    curate_shortlist,
    rank_skills,
    rank_skills_detailed,
)
from .attribution import (
    compute_skill_attributions,
    is_learnable_outcome,
)

__all__ = [
    "CanonicalSkillResolver",
    "SkillRecord",
    "normalize_skill_ref",
    "parse_skill_text",
    "slugify",
    "CATALOG_VERSION",
    "SCHEMA_VERSION",
    "CanonicalSkillCatalog",
    "CatalogValidationError",
    "apply_canonical_metadata",
    "canonical_metadata_for",
    "load_canonical_catalog",
    "validate_catalog_documents",
    "CompactSkillCard",
    "DiscoveryRequestError",
    "DiscoveryErrorView",
    "IndexDiscoveryView",
    "RootDiscoveryView",
    "RootIndexCard",
    "SearchDiscoveryView",
    "SkillDiscoveryView",
    "browse_index",
    "browse_roots",
    "discover_skills",
    "format_discovery_text",
    "inspect_skill_card",
    "is_public_skill",
    "score_skill_for_query",
    "search_skills",
    "skill_to_compact_card",
    "SkillGraph",
    "SkillGraphIndex",
    "UnknownIndexError",
    "UnknownSkillError",
    "all_indexes",
    "all_skills",
    "child_indexes",
    "get_index",
    "get_skill",
    "indexes_for_skill",
    "load_skill_graph",
    "related_skills",
    "require_index",
    "require_skill",
    "root_indexes",
    "skills_in_index",
    "suggested_foundations",
    "SkillLifecycleTracker",
    "RankedSkillScore",
    "compute_semantic_relevance",
    "curate_shortlist",
    "rank_skills",
    "rank_skills_detailed",
    "compute_skill_attributions",
    "is_learnable_outcome",
]
